name: aac_project_mk2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # 여기서 Dart SDK 버전을 2.17 이상으로 설정합니다.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  lottie: ^2.2.0
  provider: ^6.0.0
  auto_size_text: ^3.0.0
  speech_to_text: ^6.6.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - json_data_23092400.json
    - assets/aac_data.json

    - assets/animation_gps.json
    - assets/animation_load.json
    - assets/animation_stt.json

    - assets/3d_image.png
    - assets/bookstore.png
    - assets/cafe.png
    - assets/cinema.png
    - assets/convenience_store.png
    - assets/hairdresser.png
    - assets/hospital.png
    - assets/library.png
    - assets/logo.png
    - assets/mart.png
    - assets/restaurant.png
    - assets/stationery_store.png
